import argparse
from pathlib import Path

import pandas as pd

from analysis import parse_log, build_dataframe, write_csv

# Detection logic

def dictionary_attacker_ips(df: pd.DataFrame):
    invalid_fails = df[df["event_type"] == "failed_password_invalid"]
    return set(invalid_fails["ip"].dropna().unique())


def detect_guess_then_success(df: pd.DataFrame, attacker_ips):
    failed = df[df["event_type"].isin(["failed_password_valid", "failed_password_invalid"])]
    accepted = df[df["event_type"] == "accepted_password"]

    alerts = []
    for ip in attacker_ips:
        acc_from_ip = accepted[accepted["ip"] == ip].dropna(subset=["timestamp"])
        if acc_from_ip.empty:
            continue
        for _, acc in acc_from_ip.iterrows():
            user, ts = acc["user"], acc["timestamp"]
            prior_fails = failed[(failed["ip"] == ip) & (failed["user"] == user) & (failed["timestamp"] < ts)]
            alerts.append({
                "severity": "CRITICAL",
                "source_ip": ip,
                "username": user,
                "reason": "dictionary-attacking source IP achieved a successful login for a targeted account",
                "prior_failed_attempts_same_user": int(len(prior_fails)),
                "success_timestamp": ts,
                "minutes_since_last_failed_attempt": (
                    round((ts - prior_fails["timestamp"].max()).total_seconds() / 60, 1)
                    if not prior_fails.empty else None
                ),
            })
    return alerts


def detect_dictionary_attackers_without_success(df: pd.DataFrame, attacker_ips, critical_ips):
    """HIGH: dictionary-attacker IPs that have not (yet) succeeded.
    Pre-emptive -- worth blocking before they do."""
    failed = df[df["event_type"].isin(["failed_password_valid", "failed_password_invalid"])]
    alerts = []
    for ip in attacker_ips - critical_ips:
        ip_failed = failed[failed["ip"] == ip]
        alerts.append({
            "severity": "HIGH",
            "source_ip": ip,
            "username": None,
            "reason": "dictionary/scanning attacker (guessed non-existent accounts), no confirmed success yet",
            "failed_attempts": int(len(ip_failed)),
            "distinct_accounts_targeted": int(ip_failed["user"].nunique()),
        })
    return alerts


# Response rule generation

FAIL2BAN_FILTER = """# fail2ban filter -- generated by detect_and_respond.py ,atches OpenSSH failed-password lines so fail2ban's own counting can
# apply the *preventive* threshold (see jail.local) in real time. This complements, not replaces, the offline detector above: 
# the offline detector proves the pattern is real and worth automating; this filter is what makes the block happen at line-rate in production.
failregex = ^.*sshd\\[\\d+\\]: Failed password for(?: invalid user)? \\S+ from <HOST> port \\d+ ssh2$
ignoreregex =
"""

def fail2ban_jail(flagged_ips):
    ip_list = ", ".join(sorted(set(flagged_ips)))
    return f"""# fail2ban jail -- generated by detect_and_respond.py
[sshd-credential-guessing]
enabled  = true
filter   = auth-log-credential-guessing
logpath  = /var/log/auth.log
port     = ssh
maxretry = 3
findtime = 86400
bantime  = 86400
# Source IPs already confirmed as CRITICAL/HIGH in this extract's
# alerts.csv -- seeded here so they are blocked immediately on deploy,
# ahead of fail2ban re-learning the pattern from live traffic:
# {ip_list}
"""

def iptables_fallback(flagged_ips):
    lines = ["#!/bin/sh", "# Fallback manual block list -- generated by detect_and_respond.py",
             "# Use only if fail2ban is not available on the target host.", ""]
    for ip in sorted(set(flagged_ips)):
        lines.append(f"iptables -A INPUT -s {ip} -p tcp --dport 22 -j DROP")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description="Part 2 technical defensive response: detection + blocking rules.")
    ap.add_argument("--input", default="2_auth.log")
    ap.add_argument("--outdir", default="output")
    args = ap.parse_args()

    out_dir = Path(args.outdir)
    tables_dir = out_dir / "tables"
    response_dir = out_dir / "response"
    tables_dir.mkdir(parents=True, exist_ok=True)
    response_dir.mkdir(parents=True, exist_ok=True)

    events, _ = parse_log(Path(args.input))
    df = build_dataframe(events)

    attacker_ips = dictionary_attacker_ips(df)
    critical = detect_guess_then_success(df, attacker_ips)
    critical_ips = {a["source_ip"] for a in critical}
    high = detect_dictionary_attackers_without_success(df, attacker_ips, critical_ips)

    all_alerts = critical + high
    alerts_df = pd.DataFrame(all_alerts)
    alerts_df.to_csv(tables_dir / "alerts.csv", index=False)

    flagged_ips = [a["source_ip"] for a in all_alerts]
    (response_dir / "fail2ban_filter.conf").write_text(FAIL2BAN_FILTER, encoding="utf-8")
    (response_dir / "fail2ban_jail.local").write_text(fail2ban_jail(flagged_ips), encoding="utf-8")
    (response_dir / "blocklist_iptables.sh").write_text(iptables_fallback(flagged_ips), encoding="utf-8")

    print("=" * 60)
    print(f"CRITICAL alerts (guess-then-success): {len(critical)}")
    for a in critical:
        print(f"  {a['source_ip']} - {a['username']}: {a['prior_failed_attempts_same_user']} prior fails, "
              f"success {a['minutes_since_last_failed_attempt']} min after last failure")
    print(f"HIGH alerts (high-volume guessing, no confirmed success): {len(high)}")
    for a in high:
        print(f"  {a['source_ip']}: {a['failed_attempts']} failed attempts across {a['distinct_accounts_targeted']} accounts")
    print("-" * 60)
    print(f"Alerts written to: {tables_dir / 'alerts.csv'}")
    print(f"Response rules in: {response_dir}")


if __name__ == "__main__":
    main()
