#!/bin/sh
# Fallback manual block list -- generated by detect_and_respond.py
# Use only if fail2ban is not available on the target host.

iptables -A INPUT -s 198.51.100.60 -p tcp --dport 22 -j DROP
iptables -A INPUT -s 198.51.100.61 -p tcp --dport 22 -j DROP
iptables -A INPUT -s 198.51.100.62 -p tcp --dport 22 -j DROP
iptables -A INPUT -s 203.0.113.45 -p tcp --dport 22 -j DROP
iptables -A INPUT -s 203.0.113.46 -p tcp --dport 22 -j DROP
iptables -A INPUT -s 203.0.113.47 -p tcp --dport 22 -j DROP
iptables -A INPUT -s 203.0.113.48 -p tcp --dport 22 -j DROP
iptables -A INPUT -s 203.0.113.49 -p tcp --dport 22 -j DROP
